package GUI;
import Model.BadDeath;
public class BadDeathView extends javax.swing.JPanel {

  private BadDeath badModel;
  
  public BadDeathView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jL_text = new javax.swing.JLabel();

    jL_text.setText("/*Texto*/");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jL_text)
        .addContainerGap(321, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jL_text)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  //El texto del mal rollo muerte especifica que es tipo muerte.
  public void setBC(BadDeath bad) {
		this.badModel = bad;
		jL_text.setText(bad.getText());
		repaint();
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jL_text;
  // End of variables declaration//GEN-END:variables
}
