package GUI;
import Model.BadTreasureKind;
import Model.TreasureKind;
public class BadSpecificView extends javax.swing.JPanel {

  private BadTreasureKind badModel;
  
  public BadSpecificView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jL_text = new javax.swing.JLabel();
    jL_levels = new javax.swing.JLabel();
    jL_visibletreasures = new javax.swing.JLabel();
    jL_hiddentreasures = new javax.swing.JLabel();
    jL_showlevels = new javax.swing.JLabel();
    jL_showvisibletreasures = new javax.swing.JLabel();
    jL_showhiddentreasures = new javax.swing.JLabel();

    jL_text.setText("/*Texto*/");

    jL_levels.setText("Niveles:");

    jL_visibletreasures.setText("Visibles:");

    jL_hiddentreasures.setText("Ocultos:");

    jL_showlevels.setText("/*Niveles*/");

    jL_showvisibletreasures.setText("/*Visibles*/");

    jL_showhiddentreasures.setText("/*Ocultos*/");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jL_text)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jL_levels)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jL_showlevels))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jL_visibletreasures)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jL_showvisibletreasures))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jL_hiddentreasures)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jL_showhiddentreasures)))
        .addContainerGap(242, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jL_text)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jL_levels)
          .addComponent(jL_showlevels))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jL_visibletreasures)
          .addComponent(jL_showvisibletreasures))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jL_hiddentreasures)
          .addComponent(jL_showhiddentreasures))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  public void setBC(BadTreasureKind bad) {
		badModel = bad;
		jL_text.setText(bad.getText());
		jL_showlevels.setText(Integer.toString(bad.getLevels()));
		
		String listaVis = "";
		for (TreasureKind t : bad.getSpecificVisibleTreasures()) {
			listaVis += t.toString() + " ";
		}
		jL_showvisibletreasures.setText(listaVis);
		
		String listaHid = "";
		for (TreasureKind t : bad.getSpecificHiddenTreasures()) {
			listaHid += t.toString() + " ";
		}
		jL_showhiddentreasures.setText(listaHid);
		repaint();
	}
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jL_hiddentreasures;
  private javax.swing.JLabel jL_levels;
  private javax.swing.JLabel jL_showhiddentreasures;
  private javax.swing.JLabel jL_showlevels;
  private javax.swing.JLabel jL_showvisibletreasures;
  private javax.swing.JLabel jL_text;
  private javax.swing.JLabel jL_visibletreasures;
  // End of variables declaration//GEN-END:variables
}
