package GUI;
import Model.Monster;
import Model.BadConsequence;
import Model.BadDeath;
import Model.BadNumberOfTreasures;
import Model.BadTreasureKind;

public class MonsterView extends javax.swing.JPanel {

  private Monster monsterModel;
  
  public MonsterView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    prizeView = new GUI.PrizeView();
    jL_name = new javax.swing.JLabel();
    jL_level = new javax.swing.JLabel();
    jL_showlevel = new javax.swing.JLabel();
    jL_levelagainstcultist = new javax.swing.JLabel();
    jL_showlevelagainstcultist = new javax.swing.JLabel();
    jP_badconsequence = new javax.swing.JPanel();

    jL_name.setText("/*Nombre*/");

    jL_level.setText("Nivel:");

    jL_showlevel.setText("/*Nv*/");

    jL_levelagainstcultist.setText("NivelvsSectario:");

    jL_showlevelagainstcultist.setText("/*Nvs*/");

    javax.swing.GroupLayout jP_badconsequenceLayout = new javax.swing.GroupLayout(jP_badconsequence);
    jP_badconsequence.setLayout(jP_badconsequenceLayout);
    jP_badconsequenceLayout.setHorizontalGroup(
      jP_badconsequenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    jP_badconsequenceLayout.setVerticalGroup(
      jP_badconsequenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(prizeView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jP_badconsequence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jL_name)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jL_level)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jL_showlevel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jL_levelagainstcultist)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jL_showlevelagainstcultist)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 0, 0)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jL_name)
          .addComponent(jL_level)
          .addComponent(jL_showlevel)
          .addComponent(jL_levelagainstcultist)
          .addComponent(jL_showlevelagainstcultist))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(prizeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jP_badconsequence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  public void setMonster(Monster m){
    this.monsterModel = m;
    this.jL_name.setText(m.getName());
    this.jL_showlevel.setText(Integer.toString(m.getBasicValue()));
    this.jL_showlevelagainstcultist.setText((Integer.toString(m.getSpecialValue())));
    this.prizeView.setPrize(m.getPrize());
    BadConsequence bad = this.monsterModel.getBadConsequence();
    this.repaint();
    this.revalidate();//necesario porque el tamaño del badconsequence es variable
    this.jP_badconsequence.removeAll();
    if(bad instanceof BadDeath){
      BadDeathView bcView = new BadDeathView();
      bcView.setBC((BadDeath) bad);      
      this.jP_badconsequence.add(bcView);
    }else if(bad instanceof BadNumberOfTreasures){
      BadNumberView bcView = new BadNumberView();
      bcView.setBC((BadNumberOfTreasures) bad);
      this.jP_badconsequence.add(bcView);
    }else if(bad instanceof BadTreasureKind){
      BadSpecificView bcView = new BadSpecificView();
      bcView.setBC((BadTreasureKind) bad);
      this.jP_badconsequence.add(bcView);
    }    
    this.jP_badconsequence.repaint();
    this.jP_badconsequence.revalidate();
    this.repaint();
    this.revalidate();
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jL_level;
  private javax.swing.JLabel jL_levelagainstcultist;
  private javax.swing.JLabel jL_name;
  private javax.swing.JLabel jL_showlevel;
  private javax.swing.JLabel jL_showlevelagainstcultist;
  private javax.swing.JPanel jP_badconsequence;
  private GUI.PrizeView prizeView;
  // End of variables declaration//GEN-END:variables
}
