package GUI;

import Model.Napakalaki;
import Model.CombatResult;
import javax.swing.JOptionPane;

public class NapakalakiView extends javax.swing.JFrame {

  private Napakalaki napakalakiModel;

  public NapakalakiView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    monsterView = new GUI.MonsterView();
    jP_buttons = new javax.swing.JPanel();
    jB_meetmonster = new javax.swing.JButton();
    jB_combat = new javax.swing.JButton();
    jB_nextturn = new javax.swing.JButton();
    playerView = new GUI.PlayerView();
    jL_result = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jB_meetmonster.setText("Ver monstruo");
    jB_meetmonster.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jB_meetmonsterActionPerformed(evt);
      }
    });

    jB_combat.setText("Combatir");
    jB_combat.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jB_combatActionPerformed(evt);
      }
    });

    jB_nextturn.setText("Acabar turno");
    jB_nextturn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jB_nextturnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jP_buttonsLayout = new javax.swing.GroupLayout(jP_buttons);
    jP_buttons.setLayout(jP_buttonsLayout);
    jP_buttonsLayout.setHorizontalGroup(
      jP_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jP_buttonsLayout.createSequentialGroup()
        .addComponent(jB_meetmonster)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jB_combat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jB_nextturn)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    jP_buttonsLayout.setVerticalGroup(
      jP_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_buttonsLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(jP_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jB_meetmonster)
          .addComponent(jB_combat)
          .addComponent(jB_nextturn)))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(playerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(jP_buttons, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(monsterView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addComponent(jL_result))
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(playerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(16, 16, 16)
        .addComponent(monsterView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jP_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
        .addComponent(jL_result)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jB_nextturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_nextturnActionPerformed
    if (napakalakiModel.nextTurnAllowed()) {
      this.jB_nextturn.setEnabled(false);
      this.jB_meetmonster.setEnabled(true);
      this.jB_combat.setEnabled(false);
      this.jL_result.setText(" ");
      this.napakalakiModel.nextTurn();
      this.setNapakalaki(napakalakiModel);
      this.monsterView.setVisible(false);
      this.jL_result.setText("");
      this.playerView.newTurn();
    } else {
      this.jL_result.setText("No cumples las condiciones para pasar de turno.");
    }
    repaint();
    revalidate();
  }//GEN-LAST:event_jB_nextturnActionPerformed

  private void jB_combatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_combatActionPerformed
    this.jB_combat.setEnabled(false);
    this.jB_nextturn.setEnabled(true);
    CombatResult result = napakalakiModel.combat();
    switch (result) {
      case WINANDWINGAME:
        JOptionPane.showMessageDialog(this, "¡¡¡ H A S   G A N A D O   L A   P A R T I D A !!!");
        System.exit(0);
        break;
      case WIN:
        this.jL_result.setText("Ganaste el combate");
        break;
      case LOSE:
        this.jL_result.setText("Has perdido el combate, te toca cumplir el mal rollo");
        break;
      case LOSEANDESCAPE:
        this.jL_result.setText("Perdiste el combate pero has logrado escapar");
        break;
      case LOSEANDDIE:
        this.jL_result.setText("Perdiste el combate y además estás muerto");
        break;
      case LOSEANDCONVERT:
        this.jL_result.setText("Bienvenido a la secta");
        break;
    }
    playerView.afterMonster();
    playerView.setPlayer(napakalakiModel.getCurrentPlayer());
    repaint();
    revalidate();
  }//GEN-LAST:event_jB_combatActionPerformed

  private void jB_meetmonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_meetmonsterActionPerformed
    this.jB_meetmonster.setEnabled(false);
    this.jB_nextturn.setEnabled(false);
    this.jB_combat.setEnabled(true);
    this.monsterView.setVisible(true);
    this.playerView.vsMonster();
    this.repaint();
    this.revalidate();
  }//GEN-LAST:event_jB_meetmonsterActionPerformed

  public void showView() {
    this.setVisible(true);
    this.setExtendedState(MAXIMIZED_BOTH);//frame is fully maximized both = vert and horiz
  }

  public void setNapakalaki(Napakalaki nap) {
    this.napakalakiModel = nap;
    this.playerView.setNapakalaki(nap);
    this.playerView.newTurn();
    this.monsterView.setMonster(nap.getCurrentMonster());
    this.monsterView.setVisible(false);
    this.jB_nextturn.setEnabled(false);
    this.jB_combat.setEnabled(false);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jB_combat;
  private javax.swing.JButton jB_meetmonster;
  private javax.swing.JButton jB_nextturn;
  private javax.swing.JLabel jL_result;
  private javax.swing.JPanel jP_buttons;
  private GUI.MonsterView monsterView;
  private GUI.PlayerView playerView;
  // End of variables declaration//GEN-END:variables
}
