package GUI;
import java.util.ArrayList;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class PlayerNamesCapture extends javax.swing.JDialog {

  private ArrayList<String> names;
  
  public PlayerNamesCapture(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    this.addWindowListener(new WindowAdapter(){
      public void windowClosing(WindowEvent e){
        System.exit(0);
      }
    });
    names = new ArrayList();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jL_player1 = new javax.swing.JLabel();
    jL_player2 = new javax.swing.JLabel();
    jL_player3 = new javax.swing.JLabel();
    jT_player1 = new javax.swing.JTextField();
    jT_player2 = new javax.swing.JTextField();
    jT_player3 = new javax.swing.JTextField();
    jB_cancel = new javax.swing.JButton();
    jB_play = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jL_player1.setText("Player 1");

    jL_player2.setText("Player 2");

    jL_player3.setText("Player 3");

    jB_cancel.setText("Cancel");
    jB_cancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jB_cancelActionPerformed(evt);
      }
    });

    jB_play.setText("Play");
    jB_play.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jB_playActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jL_player1)
              .addComponent(jL_player2)
              .addComponent(jL_player3))
            .addGap(51, 51, 51)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jT_player1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
              .addComponent(jT_player2)
              .addComponent(jT_player3)))
          .addGroup(layout.createSequentialGroup()
            .addGap(64, 64, 64)
            .addComponent(jB_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
            .addComponent(jB_play, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(115, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(51, 51, 51)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jL_player1)
              .addComponent(jT_player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(49, 49, 49)
            .addComponent(jL_player2))
          .addComponent(jT_player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(50, 50, 50)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jL_player3)
          .addComponent(jT_player3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jB_cancel)
          .addComponent(jB_play))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jB_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelActionPerformed
    System.exit(0);
  }//GEN-LAST:event_jB_cancelActionPerformed

  private void jB_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_playActionPerformed
    names.add(jT_player1.getText());
    names.add(jT_player2.getText());
    names.add(jT_player3.getText());
    this.dispose();
  }//GEN-LAST:event_jB_playActionPerformed

  public ArrayList<String> getNames(){
   this.setVisible(true);
   return names;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jB_cancel;
  private javax.swing.JButton jB_play;
  private javax.swing.JLabel jL_player1;
  private javax.swing.JLabel jL_player2;
  private javax.swing.JLabel jL_player3;
  private javax.swing.JTextField jT_player1;
  private javax.swing.JTextField jT_player2;
  private javax.swing.JTextField jT_player3;
  // End of variables declaration//GEN-END:variables
}
