package GUI;
import Model.Prize;

public class PrizeView extends javax.swing.JPanel {

  private Prize prizeModel;
  public PrizeView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jL_prizename = new javax.swing.JLabel();
    jL_levels = new javax.swing.JLabel();
    jL_showlevels = new javax.swing.JLabel();
    jL_treasures = new javax.swing.JLabel();
    jL_showtreasures = new javax.swing.JLabel();

    jL_prizename.setText("¡Premio!");

    jL_levels.setText("Niveles:");

    jL_showlevels.setText("/*Niveles*/");

    jL_treasures.setText("Tesoros:");

    jL_showtreasures.setText("/*Tesoros*/");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jL_prizename)
        .addGap(18, 18, 18)
        .addComponent(jL_levels)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jL_showlevels)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jL_treasures)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jL_showtreasures)
        .addContainerGap(17, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jL_prizename)
          .addComponent(jL_levels)
          .addComponent(jL_showlevels)
          .addComponent(jL_treasures)
          .addComponent(jL_showtreasures))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  public void setPrize(Prize p){
    this.prizeModel = p;
    this.jL_showlevels.setText((Integer.toString(p.getLevels())));
    this.jL_showtreasures.setText((Integer.toString(p.getTreasures())));
    this.repaint();
    //this.revalidate();//no es necesario, los tamaños son fijos
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jL_levels;
  private javax.swing.JLabel jL_prizename;
  private javax.swing.JLabel jL_showlevels;
  private javax.swing.JLabel jL_showtreasures;
  private javax.swing.JLabel jL_treasures;
  // End of variables declaration//GEN-END:variables
}
