package GUI;
import Model.Treasure;
import java.awt.Color;

public class TreasureView extends javax.swing.JPanel {

  private Treasure treasureModel;
  private boolean selected;
  
  public TreasureView() {
    initComponents();
    selected = false;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jL_name = new javax.swing.JLabel();
    jL_minbonus = new javax.swing.JLabel();
    jL_showmin = new javax.swing.JLabel();
    jL_maxbonus = new javax.swing.JLabel();
    jL_showmax = new javax.swing.JLabel();
    jL_type = new javax.swing.JLabel();
    jL_showtype = new javax.swing.JLabel();
    jL_goldcoins = new javax.swing.JLabel();
    jL_showgoldcoins = new javax.swing.JLabel();

    addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        formMouseClicked(evt);
      }
    });

    jL_name.setText("/*Nombre/");

    jL_minbonus.setText("Bonus mínimo");

    jL_showmin.setText("/*Min*/");

    jL_maxbonus.setText("Bonus máximo:");

    jL_showmax.setText("/*Max*/");

    jL_type.setText("Tipo:");

    jL_showtype.setText("/*tipo*/");

    jL_goldcoins.setText("Piezas de oro:");

    jL_showgoldcoins.setText("/*Oro*/");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jL_name)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jL_minbonus)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jL_showmin))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jL_maxbonus)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jL_showmax))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jL_type)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jL_showtype))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jL_goldcoins)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jL_showgoldcoins)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jL_name)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jL_minbonus)
          .addComponent(jL_showmin))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jL_maxbonus)
          .addComponent(jL_showmax))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jL_goldcoins)
          .addComponent(jL_showgoldcoins))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jL_type)
          .addComponent(jL_showtype))
        .addGap(0, 13, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    selected = !selected;
    this.setOpaque(selected);//If true the component paints every pixel within its bounds.
    this.setBackground(Color.green);
    repaint();
  }//GEN-LAST:event_formMouseClicked

  public void setTreasure(Treasure t){
    this.treasureModel = t;
    jL_name.setText(t.getName());
    jL_showmin.setText(Integer.toString(t.getBasicValue()));
    jL_showmax.setText(Integer.toString(t.getSpecialValue()));
    jL_showgoldcoins.setText(Integer.toString(t.getGoldCoins()));
    jL_showtype.setText(t.getType().toString());
    repaint();
  }
  
  public boolean isSelected(){
    return selected;
  }
  
  public Treasure getTreasure(){
    return this.treasureModel;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jL_goldcoins;
  private javax.swing.JLabel jL_maxbonus;
  private javax.swing.JLabel jL_minbonus;
  private javax.swing.JLabel jL_name;
  private javax.swing.JLabel jL_showgoldcoins;
  private javax.swing.JLabel jL_showmax;
  private javax.swing.JLabel jL_showmin;
  private javax.swing.JLabel jL_showtype;
  private javax.swing.JLabel jL_type;
  // End of variables declaration//GEN-END:variables
}
